# -*- mode: sh; sh-shell: zsh; -*-

. "$HOME/.config/workstation/dotfiles/commonrc"

setopt append_history # append rather then overwrite
setopt extended_history # save timestamp
setopt inc_append_history # add history
